# Generated by Django 2.1.7 on 2019-03-29 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='auth.Group', verbose_name='团队')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
