# Generated by Django 2.1.7 on 2019-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='room',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='auth.Group', verbose_name='团队/组'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='科室'),
        ),
    ]
