# Generated by Django 2.1.7 on 2019-04-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190401_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brief',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='职位'),
        ),
    ]
