# Generated by Django 2.1.7 on 2019-03-29 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190329_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('id',), 'verbose_name': '团队', 'verbose_name_plural': '团队'},
        ),
        migrations.AddField(
            model_name='team',
            name='desc',
            field=models.TextField(default=None, max_length=30, verbose_name='团队描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='account.Room', verbose_name='科室'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='team', to='auth.Group', verbose_name='团队'),
        ),
    ]
