# Generated by Django 2.1.7 on 2019-03-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190329_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('id',), 'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('id',), 'verbose_name': '科室', 'verbose_name_plural': '科室'},
        ),
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='account.Room', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机'),
        ),
    ]
